---
logging:
  level:
    root: WARN
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  # mvc:
  #   log-request-details: true
  #   log-resolved-exception: true
  # codec:
  #   log-request-details: true
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always

sentry:
  dsn: https://93a45037035bb5a8fd7d9db8548f44a2@o4508914318376960.ingest.de.sentry.io/4508914325192784
  send-default-pii: true
  tracesSampleRate: 1.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  address: 0.0.0.0
  port: ${PORT:8080}